[profile.default]
solc_version = '0.8.17' # Version of solc that we use
remappings = [ # Libraries that we use from node_modules and are used by the smart contracts
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
]
optimizer = true # Enable or disable the solc optimizer
optimizer_runs = 20_000 # The number of optimizer runs
verbosity = 3 # The verbosity of tests
bytecode_hash = "none" # For deterministic code
block_timestamp = 1_622_400_000 # Timestamp for tests (non-zero)

# silence warnings
# 2462 - ignored constructor visibility in OZ dependency
ignored_error_codes = [2462]
libs = ["node_modules", "lib"]

ffi = false

[fuzz]
runs = 10_000
