[profile.default]
solc_version = '0.8.20' # Version of solc that we use
evm_version = 'shanghai'
remappings = [ # Libraries that we use from node_modules and are used by the smart contracts
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]
optimizer = true # Enable or disable the solc optimizer
optimizer_runs = 20_000 # The number of optimizer runs
verbosity = 3 # The verbosity of tests
bytecode_hash = "none" # For deterministic code
block_timestamp = 1_622_400_000 # Timestamp for tests (non-zero)

# silence warnings
# 2462 - ignored constructor visibility in OZ dependency
ignored_error_codes = [2462]
libs = ["node_modules", "lib"]

ffi = false

[fuzz]
runs = 10_000
