name: test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    foundry:
        strategy:
            fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Run Forge build
              run: |
                  forge --version
                  forge build --sizes
              id: build

            - name: Run Forge tests
              run: |
                  forge test -vvv
              id: forge-test

            - name: Run snapshot
              run: NO_COLOR=1 forge snapshot >> $GITHUB_STEP_SUMMARY

    hardhat:
        strategy:
            fail-fast: true

        name: Hardhat project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Setup Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Run Tests
              run: npm test
