name: test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    foundry:
        strategy:
            fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Run Forge build
              run: |
                  forge --version
                  forge build --sizes
              id: build

            - name: Run Forge tests
              run: |
                  forge test -vvv
              id: forge-test

            - name: Run snapshot
              run: NO_COLOR=1 forge snapshot >> $GITHUB_STEP_SUMMARY

    hardhat:
        strategy:
            fail-fast: true

        name: Hardhat project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Setup Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Run Hardhat tests
              run: |
                  pnpm run test
                  id: hardhat-test
